# Generated by Django 5.1.7 on 2025-04-25 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('usd_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kes_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tzs_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ugx_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('features', models.TextField(help_text='One feature per line')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=3)),
                ('phone_number', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=5)),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('AIRTEL', 'Airtel Money'), ('CARD', 'Credit/Debit Card')], max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=10)),
                ('transaction_id', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guest_email', models.EmailField(blank=True, max_length=254)),
                ('guest_name', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.plan')),
            ],
        ),
    ]
