# Generated by Django 5.1.7 on 2025-04-25 17:06

from django.db import migrations



from django.db import migrations

def create_initial_plans(apps, schema_editor):
    Plan = apps.get_model('payments', 'Plan')
    
    initial_plans = [
        {
            'name': 'Basic',
            'slug': 'basic',
            'usd_price': 19.99,
            'kes_price': 2800,
            'tzs_price': 46000,
            'ugx_price': 74000,
            'features': "eBook in 3 formats\nMobile friendly\nInstant download"
        },
        {
            'name': 'Standard',
            'slug': 'standard',
            'usd_price': 29.99,
            'kes_price': 4200,
            'tzs_price': 69000,
            'ugx_price': 111000,
            'features': "Everything in Basic\nWorkbook (PDF)\nCheat sheets\n3 bonus chapters"
        },
        {
            'name': 'Premium',
            'slug': 'premium',
            'usd_price': 49.99,
            'kes_price': 7000,
            'tzs_price': 115000,
            'ugx_price': 185000,
            'features': "Everything in Standard\nAudio version\n1-on-1 consultation\nLifetime updates\nPriority support"
        }
    ]
    
    for plan_data in initial_plans:
        Plan.objects.get_or_create(
            slug=plan_data['slug'],
            defaults=plan_data
        )

class Migration(migrations.Migration):

    dependencies = [
        # Add your last payment app migration here
        ('payments', '0001_initial'),  # Replace with your actual last migration
    ]

    operations = [
        migrations.RunPython(create_initial_plans),
    ]